### ISSUE TITLE
⚠️ This package appears to be abandoned.

### ISSUE THREAD

**Issue by golergka** [mattphillips/jest-expect-message#47]
Most importantly — this is not an attack on @mattphillips. Nobody's entitled to other person's labour, and open source maintainer ["is not my bitch"](https://psuvanguard.com/george-r-r-martin-is-not-your-bitch/). If he made a decision to abandon this package, it's his to make.

That said, if you plan to use this package, you should be aware that it has last been updated in 2019, and critical issues like https://github.com/mattphillips/jest-expect-message/issues/39 that prevent it from being used with new versions of Jest are not fixed, and pull request that fixes that https://github.com/mattphillips/jest-expect-message/issues/39 has been open for almost two years.

If anyone would fork this package, merge all the pull requests and release it on npm under another name, however, this would be most welcome.

**Comment by alexneo2003** [comment]
try modified package `@alex_neo/jest-expect-message`
connect to project as

``` javascript
 setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by HumbertoL** [comment]
I also made my own version of the package [`jest-27-expect-message`](https://www.npmjs.com/package/jest-27-expect-message)

It has Jest 27 support and the dependency versions have been bumped. I can look into merging other PRs into this package in the upcoming week.

EDIT: I've started merging PRs from this repo to my new package. Notably, this PR with performance improvements is now included in my package: https://github.com/mattphillips/jest-expect-message/pull/27

**Comment by mctrafik** [comment]
Can you guys add this file to your repos?

`/types/jest-expect-message.d.ts`

```typescript
declare namespace jest {
  interface Expect {
    <T = unknown>(actual: T, failMessage: string): JestMatchers<T>;
  }
}
```

This is so that typescript projects could use it.

**Comment by Anthony-Breneliere** [comment]
> I also made my own version of the package [`jest-27-expect-message`](https://www.npmjs.com/package/jest-27-expect-message)
> 
> It has Jest 27 support and the dependency versions have been bumped. I can look into merging other PRs into this package in the upcoming week.
> 
> EDIT: I've started merging PRs from this repo to my new package. Notably, this PR with performance improvements is now included in my package: #27

There issue with that project is there is no issue management on the GitHub project.

**Comment by Anthony-Breneliere** [comment]
The main reason why this package has been abandonned is that it is useless.

The rare cases where you need some result text to be linked with the test, you just need to throw the message, and jest will format it well for you.

```
if ( expect_condition )
  throw new Error( myMessage );
```
The good practice is to keep original expect functions in order to force decomposition with many expect( .. ) calls. But for those that are used to some other test framework, that feature could be missing.

**Comment by golergka** [comment]
> The main reason why this package has been abandonned is that it is useless.

Even if it was true, it would be completely irrelevant. There's a lot of projects in production that, for better or worse, have already made a decision to use this package, and these projects need to be able to upgrade to the latest Jest versions without needing to rewrite all their tests for something else.

**Comment by Anthony-Breneliere** [comment]
> Even if it was true, it would be completely irrelevant. There's a lot of projects in production that, for better or worse, have already made a decision to use this package, and these projects need to be able to upgrade to the latest Jest versions without needing to rewrite all their tests for something else.

Yes you are right, I forgot that who integrated it before. 
Maybe open source projects should have a kind of guarantor, to delegate the maintenance after a abandonment.

**Comment by mattphillips** [comment]
Thanks for your messages, this package isn't abandoned. I've just published https://www.npmjs.com/package/jest-expect-message/v/1.0.4 which includes fixes for #39 and #24 and #34.

I'll go ahead and close this issue 👍

**Comment by Anthony-Breneliere** [comment]
> Thanks for your messages, this package isn't abandoned. I've just published https://www.npmjs.com/package/jest-expect-message/v/1.0.4 which includes fixes for #39 and #24 and #34.
> 
> I'll go ahead and close this issue 👍

It is a surprise, after 4 years !

I just reverted the commit that added jest-expect-message on my current project this morning. Maybe I'll revert my revert commit tomorow morning.

**Comment by cefn** [comment]
Great to see this project coming back to life which I used in the past but stepped away from owing to lack of maintenance. Great work!

**Comment by cefn** [comment]
> The main reason why this package has been abandonned is that it is useless.
> 
> The rare cases where you need some result text to be linked with the test, you just need to throw the message, and jest will format it well for you.
> 
> ```
> if ( expect_condition )
>   throw new Error( myMessage );
> ```

@Anthony-Breneliere I would agree with you if there were a Jest API that exposed a conditional semantics (not an assertion+exception throwing semantics). 

Then we would be able to consume all of the richness of `expect(value).toFulfilSomething(special)` giving us a boolean return while implicitly documenting the intent of `.toFulfilSomething(special)` from a software team perspective (by checking the boolean and explicitly associating a message). The power of all the matchers is not to be sniffed at, and best not reimplemented from scratch.

Especially when the composition of the assertion is a bit special (why should the object be exactly that shape) I would rather guide people to use Jest expressivity, and this library ALSO gives us the means of having team-meaningful statements in test failures. For example `Session state hasn't settled - eventual consistency issue in upstream session index - check all writes are transactional` might be the real intent of `expect(context).toMatchObject({retrieval:{final:true}})` which is otherwise mystifying.

An alternative I've speculated about is to be able to catch Jest's specific expectation-matcher-failure exception, and rethrow it with the extra message attached. Once again, if Jest exposed the Exception type as part of the API this would be possible, but for now monkeypatching `expect` is the least-worst option.
